apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pqc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pqc
  template:
    metadata:
      labels:
        app: my-pqc
    spec:
      containers:
      - name: my-pqc
        image: ghcr.io/samyuan1990/trash:postcrypto