apiVersion: batch/v1
kind: Job
metadata:
  name: test
  namespace: kepler
spec:
  template:
    spec:
      containers:
      - name: test
        image: localhost:5001/keplere2etest:latest
        env:
          kepler_address: kepler-exporter:9102
      restartPolicy: Never