name: Scheduled build
on:
  branch_protection_rule:
  schedule:
    - cron: "12 9 * * *"

jobs:
  # daily go security
  gosec:
    uses: ./.github/workflows/gosec.yml
  # daily image build    
  base_image:
    uses: ./.github/workflows/image_base.yml
    with:
      push_option: false  
    secrets:
        username: ${{ secrets.BOT_NAME }}
        password: ${{ secrets.BOT_TOKEN }}
  image:
    uses: ./.github/workflows/image.yml
    secrets:
        username: ${{ secrets.BOT_NAME }}
        password: ${{ secrets.BOT_TOKEN }}
  # daily openSSF scan
  scorecard:
    uses: ./.github/workflows/scorecard.yml
  # daily rpm
  rpm:
    uses: ./.github/workflows/rpm.yml