name: Scheduled build
on:
  branch_protection_rule:
  schedule:
    - cron: "12 9 * * *"

jobs:
  gosec:
    uses: ./.github/workflows/gosec.yml
  image:
    uses: ./.github/workflows/image.yml
  scorecard:
    uses: ./.github/workflows/scorecard.yml