name: CVE to Deployment

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5

      - name: generate CVE.json
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b ./
          go install github.com/devops-kung-fu/bomber@latest 
          ./syft scan quay.io/sustainable_computing_io/kepler:latest -o cyclonedx-json -vv  > sbom.json 
          cat sbom.json
          bomber scan ./sbom.json --output=json --debug > cve.json
          cat cve.json

      - name: Test Local Action
        id: test-action
        uses: SamYuan1990/OpenAI_CodeAgent-action@main
        with:
          baseURL: https://api.deepseek.com
          apiKey: ${{ secrets.API_KEY }}
          fileOverWrite: true
          model: deepseek-chat
          dirPath: ./example
          prompt:
            please give me a pod deployment suggestion, according to CVSS 3.1
            scrore and deployment.yaml,
          maxIterations: 10
          dryRun: true
          runType: CVE2Deployment

      - name: Create new issue
        uses: imjohnbo/issue-bot@v3
        with:
          title: AutoBumpUpVersionReminder
          body: |-
            :wave: Hi maintainers, here is LLM's deployment suggested according to your CVSS scan result.
            ${{ steps.test-action.outputs.LLMresponse }}
