name: image

on:
  pull_request:

jobs:
  image_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Quay
      uses: docker/login-action@v1
      with:
        registry: quay.io/sustainable_computing_io
        username: ${{ secrets.BOT_NAME }}
        password: ${{ secrets.BOT_TOKEN }}
    - name: check go version
      run: go version
    - name: make container
      run: make
    #- name: push to quay
    #  run: podman push quay.io/sustainable_computing_io/kepler:latest