name: base

on:
  workflow_call:
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  baseimagebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
            registry: quay.io/sustainable_computing_io
            username: ${{ secrets.username }}
            password: ${{ secrets.password }}
      - name: Build and push base image
        run: ./build/build-images.sh -b
      - name: Build and push builder image
        run: ./build/build-images.sh -r
