name: local env set up

on:
  workflow_call:

jobs:
  integration_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kube_provider: [kind]
    steps:
      - uses: actions/checkout@v4
      - name: kubectl
        run: curl -LO https://dl.k8s.io/release/v1.25.4/bin/linux/amd64/kubectl
      - name: local cluster set up
        run: make cluster-up

     
