name: Push
on:
  branch_protection_rule:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'enhancements/**'
      - '*.md'

jobs:
  image:
    uses: ./.github/workflows/image.yml
  unit_test:
    uses: ./.github/workflows/unit_test.yml
  scorecard:
    uses: ./.github/workflows/scorecard.yml
